name: "01. Run Tests"
run-name: Running tests "${{ github.ref }}" by "${{ github.actor }}"
on:
  push:
    # Ignore following branches
    branches-ignore:
      - "dev/*"

jobs:
  ## Python linter check
  python-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r kedro-sklearn/src/requirements.txt
      - name: Install lint libraries
        run: |
          pip install black
          pip install isort
        # pip install pylint
      - run: black --check kedro-sklearn/src
      - run: isort --profile black --check kedro-sklearn/src
      # - run: pylint kedro-sklearn/src/kedro_sklearn

  ## Run tests
  run-tests:
    if: success() || failure()
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r kedro-sklearn/src/requirements.txt
      - run: kedro info
      - run: ls ${{ github.workspace }}
      - name: Run tests
        run: |
          cd kedro-sklearn
          kedro test
          cd ..

  ## Build package
  build-package:
    needs: [run-tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r kedro-sklearn/src/requirements.txt
      - run: kedro info
      - run: ls ${{ github.workspace }}
      - name: Create package
        run: |
          cd kedro-sklearn
          kedro package
          cd ..
      - name: Dump package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: project-package
          path: kedro-sklearn/dist
